version: '3.8'

services:
    price-analyzer:
        container_name: price-analyzer
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file: .env
        privileged: true